config/routes.rb
  Rails.application.routes.draw do
  resources :books, except: [:show]
  get 'book/:id', to: 'books#show', as: 'book_show' 
  
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'


  resources :blogs do 
    member do 
      get 'toggle_status'
    end
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    enum status: {draft: 0, published: 1}
    extend FriendlyId
    friendly_id :title, use: :slugged
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save 
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        # format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        # format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.status? = nil 
     @blog.draft!
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: [:show, :edit, :update, :destroy]
    
    
    def index 
        @book_items = Book.all
    end

    def show 
    end

    def edit 
    end
    
    def new 
        @book_item = Book.new
    end

    def create 
        @book_item = Book.new(book_params)

        respond_to do |format|
            if @book_item.save 
                format.html { redirect_to @book_item, notice: 'your book item is now live'}
            else
                format.html {render :new}
            end
        end
    end


    def update 
        respond_to do |format| 
            if @book_item.update(book_params)
                format.html { redirect_to books_path, notice: 'Se ha actualizado el book'}
            else 
                format.html {render :edit}
            end
        end
    end

    def destroy 
        @book_item.destroy 
        respond_to do |format| 
            format.html { redirect_to books_url, notice: "El book ha sido borrado"}
        end
    end
    

    
       
private 
    def set_book
        @book_item = Book.find(params[:id])
    end

    def book_params 
        params.require(:book).permit(:title, :subtitle, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
    @books = Book.all
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %> </td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/books/edit.html.erb
<%= form_with(model: @book_item, local: true) do |form| %>
    <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/index.html.erb
<h1> Book items</h1>




<% @book_items.each do |book_item| %>
<br>

<%= link_to book_item.title, book_show_path(book_item.id) %>

<%= book_item.title %>
<br>
<%= book_item.subtitle %>
<br>
<%= book_item.body %> 
<br> 
<%= image_tag book_item.thumb_image unless book_item.thumb_image.nil?%>

<%= link_to "crear book nuevo", new_book_path %>

<%= link_to "editar", edit_book_path(book_item.id) %>

<%= link_to "borrar publicación", 
book_path(book_item), 
method: :delete, data: { confirm: "¿estás seguro?"}  %>

<% end %>

app/views/books/new.html.erb
<h1> list of book publications </h1>

<%= form_with(model: @book_item, local: true) do |form| %>
    <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/show.html.erb
<%= image_tag @book_item.main_image %> 

<h1><%= @book_item.title %> </h1>

<h2> <%= @book_item.subtitle %> </h2>

<p> <%= @book_item.body %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h2> publicaciones</h2>

<% @posts.each do |post| %>
<%= post.title %>
<%= post.body %>
<% end %>

<br> 

<h2> skills </h2>

<% @skills.each do |skill| %>
<%= skill.title %>
<%= skill.percent_utilized %>
<% end %>

<h2> books </h2>

<% @books.each do |book| %>
<%= book.title %> 
<%= book.subtitle %>
<%= book.body %> 
<%= book.main_image %> 
<%= book.thumb_image %>
<% end %> 